name: saberpro-clustering
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy=1.26.4
  - pandas=2.2.2
  - scikit-learn=1.5.1
  - matplotlib=3.9.1
  - seaborn=0.13.2
  - pyyaml=6.0.1
  - pyarrow=17.0.0
  - scipy=1.13.1
  - joblib=1.4.2
  - tqdm=4.66.4
  - pytest=8.3.2
  - jupyter=1.0.0
  - pip
  - pip:
      - umap-learn==0.5.6
      - hdbscan==0.8.38.post1
      - plotly==5.23.0
